name: Medical_Expenses

on: 
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

permissions:
    contents: read

jobs:
    build:
        runs-on: unbuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Set Up Python 3.12.4
              uses: actions/checkout@v3
              with:
                python-version: "3.12.4"

            - name : Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install flake8 pytest
                if [ -f requirements.txt ]; then pip intsall -r requirements.txt; fi

            - name: Docker Build and Push
              run : |
                docker build -t medical .
                docker tag medical vrush0402/medical:latest
                docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
                docker push vrush0402/medical:latest